/**
 * Copyright IBM Corp. 2018, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Theme } from './types';

const legacyTheme: Theme = {
  /**primary button */
  primaryButtonTextColorDefault: '#fff',
  primaryButtonTextColorDisabled: '#fff',
  primaryButtonBackgroundColorDefault: '#4384F5',
  primaryButtonBackgroundColorHover: '#4379D6',
  primaryButtonBackgroundColorLoading: '#c3d7fa',
  primaryButtonBackgroundColorDisabled: '#c3d7fa',
  /**secondary button */
  secondaryButtonTextColorDefault: '#424d57',
  secondaryButtonTextColorDisabled: '',
  secondaryButtonBackgroundColorDefault: '#fff',
  secondaryButtonBackgroundColorHover: '#f9fbfb',
  secondaryButtonBackgroundColorLoading: '#fbfcfe',
  secondaryButtonBackgroundColorDisabled: '',
  secondaryButtonBorderColorDefault: '#bcc6d0',
  secondaryButtonBorderColorHover: '#bcc6d0',
  secondaryButtonBorderColorLoading: '#d0d2d5',
  secondaryButtonBorderColorDisabled: '',
  /**basic button */
  basicButtonTextColorDefault: '#4384f5',
  basicButtonTextColorDisabled: '',
  basicButtonBackgroundColorDefault: '#fff',
  basicButtonBackgroundColorHover: '#f9fbfb',
  basicButtonBackgroundColorLoading: '#fbfcfe',
  basicButtonBackgroundColorDisabled: '',
  basicButtonBorderColorDefault: '#4384f5',
  basicButtonBorderColorHover: '#4384f5',
  basicButtonBorderColorLoading: '#4384f5',
  basicButtonBorderColorDisabled: '',
  /**destructive button */
  destructiveButtonTextColorDefault: '#fff',
  destructiveButtonTextColorDisabled: '',
  destructiveButtonBackgroundColorDefault: '#d64646',
  destructiveButtonBackgroundColorHover: '#b9484a',
  destructiveButtonBackgroundColorLoading: '#eec4c5',
  destructiveButtonBackgroundColorDisabled: '#eec4c5',
  /**checkbox */
  checkboxColorSelected: '#fff',
  checkboxColorDisabled: '',
  checkboxBackgroundColorDefault: '#f3f7f9',
  checkboxBackgroundColorSelected: '#4384f5',
  checkboxBackgroundColorDisabled: '#c3d7fa',
  checkboxBorderColorDefault: '#bcc6d0',
  checkboxBorderColorSelected: '#4384f5',
  checkboxBorderColorSelectedDisabled: '#c3d7fa',
  checkboxBorderColorDisabled: '#dae3ec',
  /**radio button */
  radioButtonColorSelected: '#fff',
  radioButtonColorDisabled: '',
  radioButtonBackgroundColorDefault: '#f3f7f9',
  radioButtonBackgroundColorSelected: '#4384f5',
  radioButtonBackgroundColorDisabled: '#c3d7fa',
  radioButtonBorderColorDefault: '#bcc6d0',
  radioButtonBorderColorSelected: '#4384f5',
  radioButtonBorderColorSelectedDisabled: '#c3d7fa',
  radioButtonBorderColorDisabled: '#dae3ec',
  /**switch */
  switchColorDefault: '#fff',
  switchColorDisabled: '',
  switchBackgroundColorDefault: '#dde2e5',
  switchBackgroundColorSelected: '#4bb678',
  switchBackgroundColorSelectedDisabled: '#85d5a7',
  switchBackgroundColorDisabled: '#dae3ec',
  /**icon */
  iconColorPrimaryDefault: '#424d57',
  iconColorPrimaryDisabled: '#686d72',
  iconColorSecondaryDefault: '',
  iconColorSecondaryDisabled: '',
  iconColorInvertedDefault: '#fff',
  iconColorInvertedDisabled: '#dbdbdb',
  iconColorLinkDefault: '#4384f5',
  iconColorLinkDisabled: '#c3d7fa',
  iconColorErrorDefault: '#d64646',
  iconColorSuccessDefault: '#4bb678',
  iconColorWarningDefault: '#efa842',
  /**ButtonGroup */
  segmentedControlBackgroundColorDefault: '#fff',
  segmentedControlBackgroundColorHover: '#f3f7f9',
  segmentedControlBackgroundColorSelected: '#e1e8ed',
  segmentedControlBackgroundColorDisabled: '',
  segmentedControlBorderColorDefault: '#bcc6d0',
  segmentedControlBorderColorHover: '#bcc6d0',
  segmentedControlBorderColorSelected: '#bcc6d0',
  segmentedControlBorderColorDisabled: '',
  /**Font */
  primaryFontColor: '#424d57',
  secondaryFontColor: '#697179',
  tertiaryFontColor: '#8d9499',
  /**Input */
  inputTextColorDefault: '#424d57',
  inputBackgroundColorDefault: '#fff',
  inputBackgroundColorHover: '#fff',
  inputBackgroundColorActive: '#fff',
  inputBackgroundColorDisabled: '',
  inputBorderColorDefault: '#bcc6d0',
  inputBorderColorHover: '#a0a6ab',
  inputBorderColorActive: '#4384f5',
  inputBorderColorDisabled: '',
  /**Filter */
  filterBackgroundColor: '#59699e',
  filterTextColor: '#fff',
  /**Link */
  linkColorDefault: '#4384f5',
  linkColorHover: '#4379D6',
  /**Toast */
  toastErrorColor: '#fff',
  toastErrorBackgroundColor: '#d64646',
  toastWarningColor: '#fff',
  toastWarningBackgroundColor: '#efa842',
  toastInfoColor: '#fff',
  toastInfoBackgroundColor: '#5ca8f5',
  toastSuccessColor: '#fff',
  toastSuccessBackgroundColor: '#4bb678',
  /**Independent */
  primarySurfaceBackgroundColor: '#fff',
  dividerColor: '#dde2e6',
  uiBackgroundColorDefault: '#f3f7f9',
  uiBackgroundColorHover: '#e1e8ed',
  overlayBackgroundColor: '#000000',
  overlayTextColor: '#fff'

  // primary: '#4384f5',
  // primaryHover: '#4379d6',
  // primaryDisabled: '#c3d7fa',
  // basic: '#ffffff',
  // basicHover: '#f9fbfb',
  // basicDisabled: '#fbfcfe',
  // inactive: '#dde2e5',
  // danger: '#d64646',
  // dangerHover: '#b9484a',
  // dangerDisabled: '#eec4c5',
  // success: '#4bb678',
  // warning: '#efa842',
  // info: '#5ca8f5',
  // tip: '#424d57',
  // tipText: '#ffffff',
  // tipInverted: '#ffffff',
  // tipInvertedText: 'rgba(66, 77, 89, 1)',
  // tipImportant: '#facf50',
  // tipImportantText: 'rgba(66, 77, 89, 1)',
  // textPrimary: 'rgba(66, 77, 89, 1)',
  // textSecondary: 'rgba(66, 77, 89, 0.7)',
  // textTertiary: 'rgba(66, 77, 89, 0.5)',
  // textPlaceholder: 'rgba(66, 77, 89, 0.4)',
  // textOnPrimary: '#ffffff',
  // uiBackground: '#ffffff',
  // ui: '#f3f7f9',
  // uiHover: '#e1e9ec',
  // overlay: 'rgba(0, 0, 0, 0.5)',
  // overlayText: '#ffffff',
  // uiFilter: '#59699e',
  // divider: '#dde2e6',
  // border: '#bcc6d0',
  // borderHover: '#a0a6ab',
  // selected: '#3e7ce4',
  // highlight: '#dae7fd',
  // badgePrimary: '#d64646',
  // badgeSecondary: '#cbd4de',
  // shadow: '#424d57'
};

export default legacyTheme;
