/**
 * Copyright IBM Corp. 2018, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import Colors from '@livechat/design-system-colors';
import { Theme } from './types';

const lightTheme: Theme = {
  /**primary button */
  primaryButtonTextColorDefault: '#ffffff',
  primaryButtonTextColorDisabled: '#ffffff',
  primaryButtonBackgroundColorDefault: Colors.blue500,
  primaryButtonBackgroundColorHover: '',
  primaryButtonBackgroundColorLoading: '',
  primaryButtonBackgroundColorDisabled: '',
  /**secondary button */
  secondaryButtonTextColorDefault: '',
  secondaryButtonTextColorDisabled: '',
  secondaryButtonBackgroundColorDefault: '',
  secondaryButtonBackgroundColorHover: '',
  secondaryButtonBackgroundColorLoading: '',
  secondaryButtonBackgroundColorDisabled: '',
  secondaryButtonBorderColorDefault: '',
  secondaryButtonBorderColorHover: '',
  secondaryButtonBorderColorLoading: '',
  secondaryButtonBorderColorDisabled: '',
  /**basic button */
  basicButtonTextColorDefault: '',
  basicButtonTextColorDisabled: '',
  basicButtonBackgroundColorDefault: '',
  basicButtonBackgroundColorHover: '',
  basicButtonBackgroundColorLoading: '',
  basicButtonBackgroundColorDisabled: '',
  basicButtonBorderColorDefault: '',
  basicButtonBorderColorHover: '',
  basicButtonBorderColorLoading: '',
  basicButtonBorderColorDisabled: '',
  /**destructive button */
  destructiveButtonTextColorDefault: '',
  destructiveButtonTextColorDisabled: '',
  destructiveButtonBackgroundColorDefault: '',
  destructiveButtonBackgroundColorHover: '',
  destructiveButtonBackgroundColorLoading: '',
  destructiveButtonBackgroundColorDisabled: '',
  /**checkbox */
  checkboxColorActive: '',
  checkboxColorDisabled: '',
  checkboxBackgroundColorDefault: '',
  checkboxBackgroundColorActive: '',
  checkboxBackgroundColorDisabled: '',
  checkboxBorderColorDefault: '',
  checkboxBorderColorActive: '',
  checkboxBorderColorDisabled: '',
  /**radio button */
  radioButtonColorActive: '',
  radioButtonColorDisabled: '',
  radioButtonBackgroundColorDefault: '',
  radioButtonBackgroundColorActive: '',
  radioButtonBackgroundColorDisabled: '',
  radioButtonBorderColorDefault: '',
  radioButtonBorderColorActive: '',
  radioButtonBorderColorDisabled: '',
  /**switch */
  switchColorDefault: '',
  switchColorDisabled: '',
  switchBackgroundColorDefault: '',
  switchBackgroundColorActive: '',
  switchBackgroundColorDisabled: '',
  /**icon */
  iconColorPrimaryDefault: '',
  iconColorPrimaryDisabled: '',
  iconColorSecondaryDefault: '',
  iconColorSecondaryDisabled: '',
  iconColorInvertedDefault: '',
  iconColorInvertedDisabled: '',
  iconColorLinkDefault: '',
  iconColorLinkDisabled: '',
  iconColorErrorDefault: '',
  iconColorSuccessDefault: '',
  iconColorWarningDefault: '',
  /**ButtonGroup */
  buttonGroupBackgroundColorDefault: '',
  buttonGroupBackgroundColorHover: '',
  buttonGroupBackgroundColorLoading: '',
  buttonGroupBackgroundColorDisabled: '',
  buttonGroupBorderColorDefault: '',
  buttonGroupBorderColorHover: '',
  buttonGroupBorderColorLoading: '',
  buttonGroupBorderColorDisabled: '',
  /**Font */
  primaryFontColor: '',
  secondaryFontColor: '',
  tertiaryFontColor: '',
  /**Input */
  inputTextColorDefault: '',
  inputBackgroundColorDefault: '',
  inputBackgroundColorHover: '',
  inputBackgroundColorLoading: '',
  inputBackgroundColorDisabled: '',
  inputBorderColorDefault: '',
  inputBorderColorHover: '',
  inputBorderColorLoading: '',
  inputBorderColorDisabled: '',
  /**Filter */
  filterTextColor: '',
  filterBackgroundColor: '',
  /**Link */
  linkColorDefault: '',
  linkColorHover: '',
  /**Toast */
  toastErrorColor: '',
  toastErrorBackgroundColor: '',
  toastWarningColor: '',
  toastWarningBackgroundColor: '',
  toastInfoColor: '',
  toastInfoBackgroundColor: '',
  /**Independent */
  primarySurfaceBackgroundColorDefault: '',
  primarySurfaceBackgroundColorHover: '',
  secondarySurfaceBackgroundColorDefault: '',
  secondarySurfaceBackgroundColorHover: '',
  dividerColor: '',
  uiBackgroundColor: '',
  overlayBackgroundColor: '',
  overlayTextColor: ''

  // primary: Colors.blue500,
  // primaryHover: Colors.blue600,
  // primaryDisabled: Colors.blue100,
  // basic: '#ffffff',
  // basicHover: Colors.gray30,
  // basicDisabled: Colors.gray50,
  // inactive: Colors.gray200,
  // danger: Colors.red500,
  // dangerHover: Colors.red600,
  // dangerDisabled: Colors.red100,
  // success: Colors.green500,
  // warning: Colors.yellow500,
  // info: Colors.blue300,
  // tip: Colors.gray800,
  // tipText: '#ffffff',
  // tipInverted: '#ffffff',
  // tipInvertedText: Colors.gray900,
  // tipImportant: Colors.yellow500,
  // tipImportantText: Colors.gray900,
  // textPrimary: Colors.gray900,
  // textSecondary: Colors.gray700,
  // textTertiary: Colors.gray600,
  // textPlaceholder: Colors.gray500,
  // textOnPrimary: '#ffffff',
  // uiBackground: '#ffffff',
  // ui: Colors.gray40,
  // uiHover: Colors.gray50,
  // overlay: 'rgba(0, 0, 0, 0.5)',
  // overlayText: '#ffffff',
  // uiFilter: Colors.blue800,
  // divider: Colors.gray100,
  // border: Colors.gray200,
  // borderHover: Colors.gray400,
  // selected: Colors.blue400,
  // highlight: Colors.blue100,
  // badgePrimary: Colors.red500,
  // badgeSecondary: Colors.gray200,
  // shadow: Colors.gray800
};

export default lightTheme;
