/**
 * Copyright IBM Corp. 2018, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import Colors from '@livechat/design-system-colors';
import { Theme } from './types';

const lightTheme: Theme = {
  /**primary button */
  primaryButtonTextColorDefault: Colors.white,
  primaryButtonTextColorDisabled: Colors.gray400,
  primaryButtonBackgroundColorDefault: Colors.blue500,
  primaryButtonBackgroundColorHover: Colors.blue600,
  primaryButtonBackgroundColorLoading: Colors.blue200,
  primaryButtonBackgroundColorDisabled: Colors.blue100,
  /**secondary button */
  secondaryButtonTextColorDefault: Colors.gray900,
  secondaryButtonTextColorDisabled: '',
  secondaryButtonBackgroundColorDefault: Colors.white,
  secondaryButtonBackgroundColorHover: Colors.gray25,
  secondaryButtonBackgroundColorLoading: Colors.gray50,
  secondaryButtonBackgroundColorDisabled: '',
  secondaryButtonBorderColorDefault: Colors.gray300,
  secondaryButtonBorderColorHover: Colors.gray300,
  secondaryButtonBorderColorLoading: Colors.gray200,
  secondaryButtonBorderColorDisabled: '',
  /**basic button */
  basicButtonTextColorDefault: Colors.blue500,
  basicButtonTextColorDisabled: '',
  basicButtonBackgroundColorDefault: Colors.white,
  basicButtonBackgroundColorHover: Colors.gray25,
  basicButtonBackgroundColorLoading: Colors.gray50,
  basicButtonBackgroundColorDisabled: '',
  basicButtonBorderColorDefault: Colors.blue500,
  basicButtonBorderColorHover: Colors.blue500,
  basicButtonBorderColorLoading: Colors.blue500,
  basicButtonBorderColorDisabled: '',
  /**destructive button */
  destructiveButtonTextColorDefault: Colors.white,
  destructiveButtonTextColorDisabled: Colors.white,
  destructiveButtonBackgroundColorDefault: Colors.red500,
  destructiveButtonBackgroundColorHover: Colors.red600,
  destructiveButtonBackgroundColorLoading: Colors.red100,
  destructiveButtonBackgroundColorDisabled: Colors.red100,
  /**checkbox */
  checkboxColorSelected: Colors.white,
  checkboxColorDisabled: '',
  checkboxBackgroundColorDefault: Colors.gray50,
  checkboxBackgroundColorSelected: Colors.blue500,
  checkboxBackgroundColorDisabled: Colors.blue100,
  checkboxBorderColorDefault: Colors.gray300,
  checkboxBorderColorSelected: Colors.blue500,
  checkboxBorderColorSelectedDisabled: Colors.blue100,
  checkboxBorderColorDisabled: Colors.gray100,
  /**radio button */
  radioButtonColorSelected: Colors.white,
  radioButtonColorDisabled: '',
  radioButtonBackgroundColorDefault: Colors.gray50,
  radioButtonBackgroundColorSelected: Colors.blue500,
  radioButtonBackgroundColorDisabled: Colors.blue100,
  radioButtonBorderColorDefault: Colors.gray300,
  radioButtonBorderColorSelected: Colors.blue500,
  radioButtonBorderColorSelectedDisabled: Colors.blue100,
  radioButtonBorderColorDisabled: Colors.gray100,
  /**switch */
  switchColorDefault: Colors.white,
  switchColorDisabled: '',
  switchBackgroundColorDefault: Colors.gray200,
  switchBackgroundColorSelected: Colors.green500,
  switchBackgroundColorSelectedDisabled: Colors.green300,
  switchBackgroundColorDisabled: Colors.gray100,
  /**icon */
  iconColorPrimaryDefault: Colors.gray900,
  iconColorPrimaryDisabled: Colors.gray500,
  iconColorSecondaryDefault: '',
  iconColorSecondaryDisabled: '',
  iconColorInvertedDefault: Colors.white,
  iconColorInvertedDisabled: Colors.gray100,
  iconColorLinkDefault: Colors.blue500,
  iconColorLinkDisabled: Colors.blue100,
  iconColorErrorDefault: Colors.red500,
  iconColorSuccessDefault: Colors.green500,
  iconColorWarningDefault: Colors.yellow500,
  /**ButtonGroup */
  segmentedControlBackgroundColorDefault: Colors.white,
  segmentedControlBackgroundColorHover: Colors.gray50,
  segmentedControlBackgroundColorSelected: Colors.gray100,
  segmentedControlBackgroundColorDisabled: '',
  segmentedControlBorderColorDefault: Colors.gray300,
  segmentedControlBorderColorHover: Colors.gray300,
  segmentedControlBorderColorSelected: Colors.gray300,
  segmentedControlBorderColorDisabled: '',
  /**Font */
  primaryFontColor: Colors.gray900,
  secondaryFontColor: Colors.gray600,
  tertiaryFontColor: Colors.gray500,
  /**Input */
  inputTextColorDefault: Colors.gray900,
  inputBackgroundColorDefault: Colors.white,
  inputBackgroundColorHover: Colors.white,
  inputBackgroundColorActive: Colors.white,
  inputBackgroundColorDisabled: '',
  inputBorderColorDefault: Colors.gray300,
  inputBorderColorHover: Colors.gray400,
  inputBorderColorActive: Colors.blue500,
  inputBorderColorDisabled: '',
  /**Filter */
  filterBackgroundColor: Colors.blue800,
  filterTextColor: Colors.white,
  /**Link */
  linkColorDefault: Colors.blue500,
  linkColorHover: Colors.blue600,
  /**Toast */
  toastErrorColor: Colors.white,
  toastErrorBackgroundColor: Colors.red500,
  toastWarningColor: Colors.yellow900,
  toastWarningBackgroundColor: Colors.yellow500,
  toastInfoColor: Colors.white,
  toastInfoBackgroundColor: Colors.blue300,
  toastSuccessColor: Colors.white,
  toastSuccessBackgroundColor: Colors.green500,
  /**Independent */
  primarySurfaceBackgroundColor: Colors.white,
  dividerColor: Colors.gray100,
  uiBackgroundColorDefault: Colors.gray50,
  uiBackgroundColorHover: Colors.gray100,
  overlayBackgroundColor: Colors.gray900,
  overlayTextColor: Colors.white

  // primary: Colors.blue500,
  // primaryHover: Colors.blue600,
  // primaryDisabled: Colors.blue100,
  // basic: '#ffffff',
  // basicHover: Colors.gray30,
  // basicDisabled: Colors.gray50,
  // inactive: Colors.gray200,
  // danger: Colors.red500,
  // dangerHover: Colors.red600,
  // dangerDisabled: Colors.red100,
  // success: Colors.green500,
  // warning: Colors.yellow500,
  // info: Colors.blue300,
  // tip: Colors.gray800,
  // tipText: '#ffffff',
  // tipInverted: '#ffffff',
  // tipInvertedText: Colors.gray900,
  // tipImportant: Colors.yellow500,
  // tipImportantText: Colors.gray900,
  // textPrimary: Colors.gray900,
  // textSecondary: Colors.gray700,
  // textTertiary: Colors.gray600,
  // textPlaceholder: Colors.gray500,
  // textOnPrimary: '#ffffff',
  // uiBackground: '#ffffff',
  // ui: Colors.gray40,
  // uiHover: Colors.gray50,
  // overlay: 'rgba(0, 0, 0, 0.5)',
  // overlayText: '#ffffff',
  // uiFilter: Colors.blue800,
  // divider: Colors.gray100,
  // border: Colors.gray200,
  // borderHover: Colors.gray400,
  // selected: Colors.blue400,
  // highlight: Colors.blue100,
  // badgePrimary: Colors.red500,
  // badgeSecondary: Colors.gray200,
  // shadow: Colors.gray800
};

export default lightTheme;
