export const DesignToken = {
  Background: '--background', // deprecated
  Background01: '--background-01',
  Background02: '--background-02',
  Background03: '--background-03',
  SurfaceBasicDefault: '--surface-basic-default', // deprecated
  SurfacePrimaryDefault: '--surface-primary-default',
  SurfaceBasicSubtle: '--surface-basic-subtle', // deprecated
  SurfaceSecondaryDefault: '--surface-secondary-default',
  SurfaceSecondaryHover: '--surface-secondary-hover',
  SurfaceSecondaryActive: '--surface-secondary-active',
  SurfaceSecondaryDisabled: '--surface-secondary-disabled',
  SurfaceBasicHover: '--surface-basic-hover', // deprecated
  SurfacePrimaryHover: '--surface-primary-hover',
  SurfaceBasicActive: '--surface-basic-active', // deprecated
  SurfacePrimaryActive: '--surface-primary-active',
  SurfacePrimaryActiveColored: '--surface-primary-active-colored',
  SurfaceBasicDisabled: '--surface-basic-disabled', // deprecated
  SurfacePrimaryDisabled: '--surface-primary-disabled',
  SurfaceTertiaryDefault: '--surface-tertiary-default',
  SurfaceSecondarySubtle: '--surface-secondary-subtle', // deprecated
  SurfaceModerateDefault: '--surface-moderate-default',
  SurfaceModerateHover: '--surface-moderate-hover',
  SurfaceModerateActive: '--surface-moderate-active',
  SurfaceTertiaryHover: '--surface-tertiary-hover',
  SurfaceTertiaryActive: '--surface-tertiary-active',
  SurfaceTertiaryDisabled: '--surface-tertiary-disabled',
  SurfaceFeedbackInfo: '--surface-feedback-info', // deprecated
  SurfaceAccentEmphasisLowInfo: '--surface-accent-emphasis-low-info',
  SurfaceFeedbackNegative: '--surface-feedback-negative', // deprecated
  SurfaceAccentEmphasisLowNegative: '--surface-accent-emphasis-low-negative',
  SurfaceFeedbackWarning: '--surface-feedback-warning', // deprecated
  SurfaceAccentEmphasisLowWarning: '--surface-accent-emphasis-low-warning',
  SurfaceFeedbackPositive: '--surface-feedback-positive', // deprecated
  SurfaceAccentEmphasisLowPositive: '--surface-accent-emphasis-low-positive',
  SurfaceAccentEmphasisLowPurple: '--surface-accent-emphasis-low-purple',
  SurfaceAccentEmphasisMinInfo: '--surface-accent-emphasis-min-info',
  SurfaceAccentEmphasisMinNegative: '--surface-accent-emphasis-min-negative',
  SurfaceAccentEmphasisMinWarning: '--surface-accent-emphasis-min-warning',
  SurfaceAccentEmphasisMinPositive: '--surface-accent-emphasis-min-positive',
  SurfaceAccentEmphasisMediumPositive:
    '--surface-accent-emphasis-medium-positive',
  SurfaceAccentEmphasisMediumNegative:
    '--surface-accent-emphasis-medium-negative',
  SurfaceAccentEmphasisMinPurple: '--surface-accent-emphasis-min-purple',
  SurfaceInvertDefault: '--surface-invert-default', // deprecated
  SurfaceInvertPrimary: '--surface-invert-primary',
  SurfaceInvertSubtle: '--surface-invert-subtle', // deprecated
  SurfaceInvertSecondary: '--surface-invert-secondary',
  SurfaceInvertDisabled: '--surface-invert-disabled',
  SurfaceLockedDefault: '--surface-locked-default',
  SurfaceLockedHover: '--surface-locked-hover',
  SurfaceLockedActive: '--surface-locked-active',
  SurfaceLockedDisabled: '--surface-locked-disabled',
  SurfaceLockedWhite: '--surface-locked-white',
  SurfaceLockedBlack: '--surface-locked-black',
  SurfaceAccentEmphasisHighInfo: '--surface-accent-emphasis-high-info',
  SurfaceAccentEmphasisHighNegative: '--surface-accent-emphasis-high-negative',
  SurfaceAccentEmphasisHighWarning: '--surface-accent-emphasis-high-warning',
  SurfaceAccentEmphasisHighPositive: '--surface-accent-emphasis-high-positive',
  SurfaceAccentEmphasisHighPurple: '--surface-accent-emphasis-high-purple',
  SurfaceOverlay: '--surface-overlay', // deprecated
  SurfaceOtherOverlay: '--surface-other-overlay',
  SurfaceOtherAgent: '--surface-other-agent',
  SurfaceOtherSkeleton: '--surface-other-skeleton',
  SurfaceGradient01: '--surface-gradient-01',
  SurfaceGradient02: '--surface-gradient-02',
  ContentDefault: '--content-default', // deprecated
  ContentBasicPrimary: '--content-basic-primary',
  ContentSubtle: '--content-subtle', // deprecated
  ContentBasicSecondary: '--content-basic-secondary',
  ContentDisabled: '--content-disabled', // deprecated
  ContentBasicDisabled: '--content-basic-disabled',
  ContentBasicNegative: '--content-basic-negative',
  ContentBasicWarning: '--content-basic-warning',
  ContentBasicPositive: '--content-basic-positive',
  ContentBasicInfo: '--content-basic-info',
  ContentBasicPurple: '--content-basic-purple',
  ContentBasicGradient01: '--content-basic-gradient-01',
  ContentWhiteLocked: '--content-white-locked', // deprecated
  ContentLockedWhite: '--content-locked-white',
  ContentBlackLocked: '--content-black-locked', // deprecated
  ContentLockedBlack: '--content-locked-black',
  ContentLockedDefault: '--content-locked-default',
  ContentLockedHover: '--content-locked-hover',
  ContentLockedActive: '--content-locked-active',
  ContentLockedDisabled: '--content-locked-disabled',
  ContentInvertDefault: '--content-invert-default', // deprecated
  ContentInvertPrimary: '--content-invert-primary',
  ContentInvertSubtle: '--content-invert-subtle', // deprecated
  ContentInvertSecondary: '--content-invert-secondary',
  ContentInvertDisabled: '--content-invert-disabled',
  ContentInvertGradient01: '--content-invert-gradient-01',
  BorderDefault: '--border-default', // deprecated
  BorderBasicPrimary: '--border-basic-primary',
  BorderBasicSecondary: '--border-basic-secondary',
  BorderSubtle: '--border-subtle', // deprecated
  BorderBasicTertiary: '--border-basic-tertiary',
  BorderHover: '--border-hover', // deprecated
  BorderBasicHover: '--border-basic-hover',
  BorderDisabled: '--border-disabled', // deprecated
  BorderBasicDisabled: '--border-basic-disabled',
  BorderBasicNegative: '--border-basic-negative',
  BorderBasicWarning: '--border-basic-warning',
  BorderBasicPositive: '--border-basic-positive',
  BorderBasicInfo: '--border-basic-info',
  BorderBasicPurple: '--border-basic-purple',
  BorderInvertDefault: '--border-invert-default', // deprecated
  BorderInvertPrimary: '--border-invert-primary',
  BorderInvertSubtle: '--border-invert-subtle', // deprecated
  BorderInvertSecondary: '--border-invert-secondary',
  BorderInvertHover: '--border-invert-hover',
  BorderInvertDisabled: '--border-invert-disabled',
  ColorActionActive: '--color-action-active', // deprecated
  ActionPrimaryActive: '--action-primary-active',
  ColorActionHover: '--color-action-hover', // deprecated
  ActionPrimaryHover: '--action-primary-hover',
  ColorActionDefault: '--color-action-default', // deprecated
  ActionPrimaryDefault: '--action-primary-default',
  ColorActionDefaultRgb: '--color-action-default-rgb',
  ColorActionDisabled: '--color-action-disabled', // deprecated
  ActionPrimaryDisabled: '--action-primary-disabled',
  ColorNegativeActive: '--color-negative-active', // deprecated
  ActionNegativeActive: '--action-negative-active',
  ColorNegativeHover: '--color-negative-hover', // deprecated
  ActionNegativeHover: '--action-negative-hover',
  ColorNegativeDefault: '--color-negative-default', // deprecated
  ActionNegativeDefault: '--action-negative-default',
  ColorNegativeDisabled: '--color-negative-disabled', // deprecated
  ActionNegativeDisabled: '--action-negative-disabled',
  ColorWarningDefault: '--color-warning-default', // deprecated
  ActionWarningDefault: '--action-warning-default',
  ColorWarningHover: '--color-warning-hover', // deprecated
  ActionWarningHover: '--action-warning-hover',
  ColorPositiveDefault: '--color-positive-default', // deprecated
  ActionPositiveDefault: '--action-positive-default',
  ColorPositiveHover: '--color-positive-hover', // deprecated
  ActionPositiveHover: '--action-positive-hover',
  ColorPositiveDisabled: '--color-positive-disabled', // deprecated
  ActionPositiveDisabled: '--action-positive-disabled',
  ActionNeutralDefault: '--action-neutral-default',
  ActionNeutralHover: '--action-neutral-hover',
  ActionNeutralDisabled: '--action-neutral-disabled',
  ColorBot: '--color-bot', // deprecated
  SurfaceOtherBot: '--surface-other-bot',
  ColorBlack: '--color-black',
  ColorWhite: '--color-white',
  DecorBlue900: '--decor-blue900',
  DecorBlue800: '--decor-blue800',
  DecorBlue700: '--decor-blue700',
  DecorBlue600: '--decor-blue600',
  DecorBlue500: '--decor-blue500',
  DecorBlue400: '--decor-blue400',
  DecorBlue300: '--decor-blue300',
  DecorBlue200: '--decor-blue200',
  DecorBlue100: '--decor-blue100',
  DecorBlue50: '--decor-blue50',
  DecorOrange900: '--decor-orange900',
  DecorOrange800: '--decor-orange800',
  DecorOrange700: '--decor-orange700',
  DecorOrange600: '--decor-orange600',
  DecorOrange500: '--decor-orange500',
  DecorOrange400: '--decor-orange400',
  DecorOrange300: '--decor-orange300',
  DecorOrange200: '--decor-orange200',
  DecorOrange100: '--decor-orange100',
  DecorOrange50: '--decor-orange50',
  DecorYellow900: '--decor-yellow900',
  DecorYellow800: '--decor-yellow800',
  DecorYellow700: '--decor-yellow700',
  DecorYellow600: '--decor-yellow600',
  DecorYellow500: '--decor-yellow500',
  DecorYellow400: '--decor-yellow400',
  DecorYellow300: '--decor-yellow300',
  DecorYellow200: '--decor-yellow200',
  DecorYellow100: '--decor-yellow100',
  DecorYellow50: '--decor-yellow50',
  DecorGray950: '--decor-gray950',
  DecorGray900: '--decor-gray900',
  DecorGray800: '--decor-gray800',
  DecorGray700: '--decor-gray700',
  DecorGray600: '--decor-gray600',
  DecorGray500: '--decor-gray500',
  DecorGray400: '--decor-gray400',
  DecorGray300: '--decor-gray300',
  DecorGray200: '--decor-gray200',
  DecorGray150: '--decor-gray150',
  DecorGray100: '--decor-gray100',
  DecorGray75: '--decor-gray75',
  DecorGray50: '--decor-gray50',
  DecorGray40: '--decor-gray40',
  DecorGray20: '--decor-gray20',
  DecorGreen900: '--decor-green900',
  DecorGreen800: '--decor-green800',
  DecorGreen700: '--decor-green700',
  DecorGreen600: '--decor-green600',
  DecorGreen500: '--decor-green500',
  DecorGreen400: '--decor-green400',
  DecorGreen300: '--decor-green300',
  DecorGreen200: '--decor-green200',
  DecorGreen100: '--decor-green100',
  DecorGreen50: '--decor-green50',
  DecorRed900: '--decor-red900',
  DecorRed800: '--decor-red800',
  DecorRed700: '--decor-red700',
  DecorRed600: '--decor-red600',
  DecorRed500: '--decor-red500',
  DecorRed400: '--decor-red400',
  DecorRed300: '--decor-red300',
  DecorRed200: '--decor-red200',
  DecorRed100: '--decor-red100',
  DecorRed50: '--decor-red50',
  DecorPurple900: '--decor-purple900',
  DecorPurple800: '--decor-purple800',
  DecorPurple700: '--decor-purple700',
  DecorPurple600: '--decor-purple600',
  DecorPurple500: '--decor-purple500',
  DecorPurple400: '--decor-purple400',
  DecorPurple300: '--decor-purple300',
  DecorPurple200: '--decor-purple200',
  DecorPurple100: '--decor-purple100',
  DecorPurple50: '--decor-purple50',
  ProductsLivechat: '--products-livechat',
  ProductsHelpdesk: '--products-helpdesk',
  ProductsChatbot: '--products-chatbot',
  ProductsKnowledgebase: '--products-knowledgebase',
  IllustrationsPrimary: '--illustrations-primary',
  IllustrationsSecondary: '--illustrations-secondary',
  IllustrationsStroke: '--illustrations-stroke',
  TagSurface01: '--tag-surface-01',
  TagContent01: '--tag-content-01',
};
