export const DesignToken = {
  /** @deprecated */
  Background: '--background',
  Background01: '--background-01',
  Background02: '--background-02',
  Background03: '--background-03',
  /** @deprecated */
  SurfaceBasicDefault: '--surface-basic-default',
  SurfacePrimaryDefault: '--surface-primary-default',
  /** @deprecated */
  SurfaceBasicSubtle: '--surface-basic-subtle',
  SurfaceSecondaryDefault: '--surface-secondary-default',
  SurfaceSecondaryHover: '--surface-secondary-hover',
  SurfaceSecondaryActive: '--surface-secondary-active',
  SurfaceSecondaryDisabled: '--surface-secondary-disabled',
  /** @deprecated */
  SurfacePrimaryHoverOpacity: '--surface-primary-hover-opacity',
  /** @deprecated */
  SurfaceBasicHover: '--surface-basic-hover',
  SurfacePrimaryHover: '--surface-primary-hover',
  /** @deprecated */
  SurfaceBasicActive: '--surface-basic-active',
  SurfacePrimaryActive: '--surface-primary-active',
  SurfacePrimaryActiveColored: '--surface-primary-active-colored',
  /** @deprecated */
  SurfaceBasicDisabled: '--surface-basic-disabled',
  SurfacePrimaryDisabled: '--surface-primary-disabled',
  SurfaceTertiaryDefault: '--surface-tertiary-default',
  /** @deprecated */
  SurfaceSecondarySubtle: '--surface-secondary-subtle',
  SurfaceModerateDefault: '--surface-moderate-default',
  SurfaceModerateHover: '--surface-moderate-hover',
  SurfaceModerateActive: '--surface-moderate-active',
  SurfaceTertiaryHover: '--surface-tertiary-hover',
  SurfaceTertiaryActive: '--surface-tertiary-active',
  SurfaceTertiaryDisabled: '--surface-tertiary-disabled',
  /** @deprecated */
  SurfaceFeedbackInfo: '--surface-feedback-info',
  SurfaceAccentEmphasisLowInfo: '--surface-accent-emphasis-low-info',
  /** @deprecated */
  SurfaceFeedbackNegative: '--surface-feedback-negative',
  SurfaceAccentEmphasisLowNegative: '--surface-accent-emphasis-low-negative',
  /** @deprecated */
  SurfaceFeedbackWarning: '--surface-feedback-warning',
  SurfaceAccentEmphasisLowWarning: '--surface-accent-emphasis-low-warning',
  /** @deprecated */
  SurfaceFeedbackPositive: '--surface-feedback-positive',
  SurfaceAccentEmphasisLowPositive: '--surface-accent-emphasis-low-positive',
  SurfaceAccentEmphasisLowPurple: '--surface-accent-emphasis-low-purple',
  SurfaceAccentEmphasisMinInfo: '--surface-accent-emphasis-min-info',
  SurfaceAccentEmphasisMinNegative: '--surface-accent-emphasis-min-negative',
  SurfaceAccentEmphasisMinWarning: '--surface-accent-emphasis-min-warning',
  SurfaceAccentEmphasisMinPositive: '--surface-accent-emphasis-min-positive',
  SurfaceAccentEmphasisMinPurple: '--surface-accent-emphasis-min-purple',
  SurfaceAccentOndarkNegativeDefault:
    '--surface-accent-ondark-negative-default',
  SurfaceAccentOndarkNegativeHover: '--surface-accent-ondark-negative-hover',
  SurfaceAccentOndarkWarningDefault: '--surface-accent-ondark-warning-default',
  SurfaceAccentOndarkWarningHover: '--surface-accent-ondark-warning-hover',
  SurfaceAccentOndarkInfoDefault: '--surface-accent-ondark-info-default',
  SurfaceAccentOndarkInfoHover: '--surface-accent-ondark-info-hover',
  SurfaceAccentOndarkPositiveDefault:
    '--surface-accent-ondark-positive-default',
  SurfaceAccentOndarkPositiveHover: '--surface-accent-ondark-positive-hover',
  SurfaceAccentEmphasisSubtleNegative:
    '--surface-accent-emphasis-subtle-negative',
  SurfaceAccentEmphasisSubtleWarning:
    '--surface-accent-emphasis-subtle-warning',
  SurfaceAccentEmphasisSubtleInfo: '--surface-accent-emphasis-subtle-info',
  SurfaceAccentEmphasisSubtlePositive:
    '--surface-accent-emphasis-subtle-positive',
  /** @deprecated */
  SurfaceInvertDefault: '--surface-invert-default',
  SurfaceInvertPrimary: '--surface-invert-primary',
  /** @deprecated */
  SurfaceInvertSubtle: '--surface-invert-subtle',
  SurfaceInvertSecondary: '--surface-invert-secondary',
  SurfaceInvertDisabled: '--surface-invert-disabled',
  SurfaceLockedDefault: '--surface-locked-default',
  SurfaceLockedHover: '--surface-locked-hover',
  SurfaceLockedActive: '--surface-locked-active',
  SurfaceLockedDisabled: '--surface-locked-disabled',
  SurfaceLockedWhite: '--surface-locked-white',
  SurfaceLockedBlack: '--surface-locked-black',
  SurfaceAccentEmphasisMediumNegative:
    '--surface-accent-emphasis-medium-negative',
  SurfaceAccentEmphasisMediumPositive:
    '--surface-accent-emphasis-medium-positive',
  SurfaceAccentEmphasisHighInfo: '--surface-accent-emphasis-high-info',
  SurfaceAccentEmphasisHighNegative: '--surface-accent-emphasis-high-negative',
  SurfaceAccentEmphasisHighWarning: '--surface-accent-emphasis-high-warning',
  SurfaceAccentEmphasisHighPositive: '--surface-accent-emphasis-high-positive',
  SurfaceAccentEmphasisHighPurple: '--surface-accent-emphasis-high-purple',
  SurfaceOpacityBasicHover: '--surface-opacity-basic-hover',
  SurfaceOpacityBasicActive: '--surface-opacity-basic-active',
  SurfaceOpacityInvertHover: '--surface-opacity-invert-hover',
  SurfaceOpacityInvertActive: '--surface-opacity-invert-active',
  /** @deprecated */
  SurfaceOverlay: '--surface-overlay',
  SurfaceGradient01: '--surface-gradient-01',
  SurfaceGradient02: '--surface-gradient-02',
  SurfaceGradient03: '--surface-gradient-03',
  SurfaceGradient04: '--surface-gradient-04',
  SurfaceGradient05: '--surface-gradient-05',
  SurfaceGradient06: '--surface-gradient-06',
  SurfaceGradient07: '--surface-gradient-07',
  SurfaceGradient08: '--surface-gradient-08',
  SurfaceGradient09: '--surface-gradient-09',
  SurfaceGradient10: '--surface-gradient-10',
  SurfaceGradient11: '--surface-gradient-11',
  SurfaceGradient12: '--surface-gradient-12',
  SurfaceGradient13: '--surface-gradient-13',
  SurfaceGradient14: '--surface-gradient-14',
  SurfaceOtherOverlay: '--surface-other-overlay',
  SurfaceOtherAgent: '--surface-other-agent',
  SurfaceOtherAgentHover: '--surface-other-agent-hover',
  SurfaceOtherSkeleton: '--surface-other-skeleton',
  /** @deprecated */
  SurfaceOtherInternalNote: '--surface-other-internal-note',
  SurfaceOtherInternalNoteHover: '--surface-other-internal-note-hover',
  SurfaceOtherVisitor: '--surface-other-visitor',
  SurfaceOtherVisitorHover: '--surface-other-visitor-hover',
  /** @deprecated */
  ContentDefault: '--content-default',
  ContentBasicPrimary: '--content-basic-primary',
  /** @deprecated */
  ContentSubtle: '--content-subtle',
  ContentBasicSecondary: '--content-basic-secondary',
  /** @deprecated */
  ContentDisabled: '--content-disabled',
  ContentBasicDisabled: '--content-basic-disabled',
  ContentBasicNegative: '--content-basic-negative',
  ContentBasicWarning: '--content-basic-warning',
  ContentBasicPositive: '--content-basic-positive',
  ContentBasicInfo: '--content-basic-info',
  ContentBasicPurple: '--content-basic-purple',
  ContentBasicGradient01: '--content-basic-gradient-01',
  /** @deprecated */
  ContentWhiteLocked: '--content-white-locked',
  ContentLockedWhite: '--content-locked-white',
  /** @deprecated */
  ContentBlackLocked: '--content-black-locked',
  ContentLockedBlack: '--content-locked-black',
  ContentLockedDefault: '--content-locked-default',
  ContentLockedHover: '--content-locked-hover',
  ContentLockedActive: '--content-locked-active',
  ContentLockedDisabled: '--content-locked-disabled',
  /** @deprecated */
  ContentInvertDefault: '--content-invert-default',
  ContentInvertPrimary: '--content-invert-primary',
  /** @deprecated */
  ContentInvertSubtle: '--content-invert-subtle',
  ContentInvertSecondary: '--content-invert-secondary',
  ContentInvertDisabled: '--content-invert-disabled',
  ContentInvertGradient01: '--content-invert-gradient-01',
  /** @deprecated */
  BorderDefault: '--border-default',
  BorderBasicPrimary: '--border-basic-primary',
  BorderBasicSecondary: '--border-basic-secondary',
  /** @deprecated */
  BorderSubtle: '--border-subtle',
  BorderBasicTertiary: '--border-basic-tertiary',
  /** @deprecated */
  BorderHover: '--border-hover',
  BorderBasicHover: '--border-basic-hover',
  /** @deprecated */
  BorderDisabled: '--border-disabled',
  BorderBasicDisabled: '--border-basic-disabled',
  BorderBasicNegative: '--border-basic-negative',
  BorderBasicWarning: '--border-basic-warning',
  BorderBasicPositive: '--border-basic-positive',
  BorderBasicInfo: '--border-basic-info',
  BorderBasicPurple: '--border-basic-purple',
  BorderBasicContrast: '--border-basic-contrast',
  /** @deprecated */
  BorderInvertDefault: '--border-invert-default',
  BorderInvertPrimary: '--border-invert-primary',
  /** @deprecated */
  BorderInvertSubtle: '--border-invert-subtle',
  BorderInvertSecondary: '--border-invert-secondary',
  BorderInvertHover: '--border-invert-hover',
  BorderInvertDisabled: '--border-invert-disabled',
  /** @deprecated */
  ColorActionActive: '--color-action-active',
  ActionPrimaryActive: '--action-primary-active',
  /** @deprecated */
  ColorActionHover: '--color-action-hover',
  ActionPrimaryHover: '--action-primary-hover',
  /** @deprecated */
  ColorActionDefault: '--color-action-default',
  ActionPrimaryDefault: '--action-primary-default',
  ColorActionDefaultRgb: '--color-action-default-rgb',
  /** @deprecated */
  ColorActionDisabled: '--color-action-disabled',
  ActionPrimaryDisabled: '--action-primary-disabled',
  /** @deprecated */
  ColorNegativeActive: '--color-negative-active',
  ActionNegativeActive: '--action-negative-active',
  /** @deprecated */
  ColorNegativeHover: '--color-negative-hover',
  ActionNegativeHover: '--action-negative-hover',
  /** @deprecated */
  ColorNegativeDefault: '--color-negative-default',
  ActionNegativeDefault: '--action-negative-default',
  /** @deprecated */
  ColorNegativeDisabled: '--color-negative-disabled',
  ActionNegativeDisabled: '--action-negative-disabled',
  /** @deprecated */
  ColorWarningDefault: '--color-warning-default',
  ActionWarningDefault: '--action-warning-default',
  /** @deprecated */
  ColorWarningHover: '--color-warning-hover',
  ActionWarningHover: '--action-warning-hover',
  ActionWarningDisabled: '--action-warning-disabled',
  /** @deprecated */
  ColorPositiveDefault: '--color-positive-default',
  ActionPositiveDefault: '--action-positive-default',
  /** @deprecated */
  ColorPositiveHover: '--color-positive-hover',
  ActionPositiveHover: '--action-positive-hover',
  /** @deprecated */
  ColorPositiveDisabled: '--color-positive-disabled',
  ActionPositiveDisabled: '--action-positive-disabled',
  ActionNeutralDefault: '--action-neutral-default',
  ActionNeutralHover: '--action-neutral-hover',
  ActionNeutralDisabled: '--action-neutral-disabled',
  ActionHighContrastDefault: '--action-high-contrast-default',
  ActionHighContrastHover: '--action-high-contrast-hover',
  ActionHighContrastActive: '--action-high-contrast-active',
  ActionHighContrastDisabled: '--action-high-contrast-disabled',
  /** @deprecated */
  ColorBot: '--color-bot',
  SurfaceOtherBot: '--surface-other-bot',
  SurfaceOtherBotHover: '--surface-other-bot-hover',
  ColorBlack: '--color-black',
  ColorWhite: '--color-white',
  DecorBlue900: '--decor-blue900',
  DecorBlue800: '--decor-blue800',
  DecorBlue700: '--decor-blue700',
  DecorBlue600: '--decor-blue600',
  DecorBlue500: '--decor-blue500',
  DecorBlue400: '--decor-blue400',
  DecorBlue300: '--decor-blue300',
  DecorBlue200: '--decor-blue200',
  DecorBlue100: '--decor-blue100',
  DecorBlue50: '--decor-blue50',
  DecorOrange900: '--decor-orange900',
  DecorOrange800: '--decor-orange800',
  DecorOrange700: '--decor-orange700',
  DecorOrange600: '--decor-orange600',
  DecorOrange500: '--decor-orange500',
  DecorOrange400: '--decor-orange400',
  DecorOrange300: '--decor-orange300',
  DecorOrange200: '--decor-orange200',
  DecorOrange100: '--decor-orange100',
  DecorOrange50: '--decor-orange50',
  DecorYellow900: '--decor-yellow900',
  DecorYellow800: '--decor-yellow800',
  DecorYellow700: '--decor-yellow700',
  DecorYellow600: '--decor-yellow600',
  DecorYellow500: '--decor-yellow500',
  DecorYellow400: '--decor-yellow400',
  DecorYellow300: '--decor-yellow300',
  DecorYellow200: '--decor-yellow200',
  DecorYellow100: '--decor-yellow100',
  DecorYellow50: '--decor-yellow50',
  DecorGray950: '--decor-gray950',
  DecorGray900: '--decor-gray900',
  DecorGray800: '--decor-gray800',
  DecorGray700: '--decor-gray700',
  DecorGray600: '--decor-gray600',
  DecorGray500: '--decor-gray500',
  DecorGray400: '--decor-gray400',
  DecorGray300: '--decor-gray300',
  DecorGray200: '--decor-gray200',
  DecorGray150: '--decor-gray150',
  DecorGray100: '--decor-gray100',
  DecorGray75: '--decor-gray75',
  DecorGray50: '--decor-gray50',
  DecorGray40: '--decor-gray40',
  DecorGray20: '--decor-gray20',
  DecorGreen900: '--decor-green900',
  DecorGreen800: '--decor-green800',
  DecorGreen700: '--decor-green700',
  DecorGreen600: '--decor-green600',
  DecorGreen500: '--decor-green500',
  DecorGreen400: '--decor-green400',
  DecorGreen300: '--decor-green300',
  DecorGreen200: '--decor-green200',
  DecorGreen100: '--decor-green100',
  DecorGreen50: '--decor-green50',
  DecorRed900: '--decor-red900',
  DecorRed800: '--decor-red800',
  DecorRed700: '--decor-red700',
  DecorRed600: '--decor-red600',
  DecorRed500: '--decor-red500',
  DecorRed400: '--decor-red400',
  DecorRed300: '--decor-red300',
  DecorRed200: '--decor-red200',
  DecorRed100: '--decor-red100',
  DecorRed50: '--decor-red50',
  DecorPurple900: '--decor-purple900',
  DecorPurple800: '--decor-purple800',
  DecorPurple700: '--decor-purple700',
  DecorPurple600: '--decor-purple600',
  DecorPurple500: '--decor-purple500',
  DecorPurple400: '--decor-purple400',
  DecorPurple300: '--decor-purple300',
  DecorPurple200: '--decor-purple200',
  DecorPurple100: '--decor-purple100',
  DecorPurple50: '--decor-purple50',
  DecorBrown50: '--decor-brown50',
  DecorBrown300: '--decor-brown300',
  ProductsLivechat: '--products-livechat',
  ProductsHelpdesk: '--products-helpdesk',
  ProductsChatbot: '--products-chatbot',
  ProductsKnowledgebase: '--products-knowledgebase',
  IllustrationsPrimary: '--illustrations-primary',
  IllustrationsSecondary: '--illustrations-secondary',
  IllustrationsStroke: '--illustrations-stroke',
  TagSurface01: '--tag-surface-01',
  TagContent01: '--tag-content-01',
  BtnBasicBackgroundEnabled: '--btn-basic-background-enabled',
  BtnBasicBackgroundHover: '--btn-basic-background-hover',
  BtnBasicBackgroundDisabled: '--btn-basic-background-disabled',
  BtnBasicBackgroundActive: '--btn-basic-background-active',
  BtnBasicBackgroundLoading: '--btn-basic-background-loading',
  BtnSecondaryBackgroundEnabled: '--btn-secondary-background-enabled',
  BtnSecondaryBackgroundHover: '--btn-secondary-background-hover',
  BtnSecondaryBackgroundDisabled: '--btn-secondary-background-disabled',
  BtnSecondaryBackgroundActive: '--btn-secondary-background-active',
  BtnSecondaryBackgroundLoading: '--btn-secondary-background-loading',
  BtnPlainIconBackgroundHover: '--btn-plain-icon-background-hover',
  BtnPlainIconBackgroundActive: '--btn-plain-icon-background-active',
  PickerListBackground: '--picker-list-background',
  PickerListGroupBackground: '--picker-list-group-background',
  PickerListOptionBackgroundHover: '--picker-list-option-background-hover',
  PickerListOptionBackgroundActiveHover:
    '--picker-list-option-background-active-hover',
  PickerListOptionBackgroundFocus: '--picker-list-option-background-focus',
  PickerListOptionBackgroundActive: '--picker-list-option-background-active',
  PopoverBackground: '--popover-background',
  SurfaceAvatar1: '--surface-avatar-1',
  SurfaceAvatar2: '--surface-avatar-2',
  SurfaceAvatar3: '--surface-avatar-3',
  SurfaceAvatar4: '--surface-avatar-4',
  SurfaceAvatar5: '--surface-avatar-5',
  SurfaceAvatar6: '--surface-avatar-6',
  SurfaceAvatar7: '--surface-avatar-7',
  SurfaceAvatar8: '--surface-avatar-8',
  SurfaceAvatar9: '--surface-avatar-9',
  SurfaceAvatar10: '--surface-avatar-10',
  NavbarBackground: '--navbar-background',
  TooltipBackgroundBasic: '--tooltip-background-basic',
  TooltipBackgroundInvert: '--tooltip-background-invert',
  TooltipBorder: '--tooltip-border',
  TooltipBorderForSvg: '--tooltip-border-for-svg',
  AnimatedGradientValue1: '--animated-gradient-value-1',
  AnimatedGradientValue2: '--animated-gradient-value-2',
  AnimatedGradientValue3: '--animated-gradient-value-3',
  ContentBasicInternalNote: '--content-basic-internal-note',
  ContentBasicBot: '--content-basic-bot',
  ActionLockDefault: '--action-lock-default',
  ActionLockHover: '--action-lock-hover',
  ActionLockActive: '--action-lock-active',
  ActionLockDisabled: '--action-lock-disabled',
  SurfaceOtherInternalNoteMessageArea:
    '--surface-other-internal-note-message-area',
  SurfaceOtherInternalNoteDefault: '--surface-other-internal-note-default',
  ContentBasicInternalNoteMessagePlaceholder:
    '--content-basic-internal-note-message-placeholder',
  ContentBasicInternalNoteMessageActive:
    '--content-basic-internal-note-message-active',
  OnePopoverMessageBackgroundDefault:
    '--one-popover-message-background-default',
  OnePopoverBorderDefault: '--one-popover-border-default',
  OnePopoverBorderActive: '--one-popover-border-active',
};

export type DesignTokenKey = keyof typeof DesignToken;
