name: Release

on:
  push:
    branches:
      - feature/v2-build-test

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch (release)
        uses: actions/checkout@v2
        with:
          ref: feature/v2-build-test

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install modules
        run: npm ci

      - name: Build icons
        run: npm run build:icons

      - name: Lerna version
        run: lerna version --conventional-commits --no-changelog --no-git-tag-version --no-push --yes

      - name: Display modified files
        run: git status --short

      - name: Display detailed diff
        run: git diff

      - name: Run tests
        run: npm run test

